language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - CI=false npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "E90sZN0ahAn2x09YzvNarE1Bdqv38Z0BLq0ql5I98kw/Qwn8BVj98V5zCnduvr5tHYYId1Pe9s5a8C0H9NIjGUQ9CikrglMCy+nbi40zBlFMN7ydyKnbLd8bTGxlAEcPuGZY/Z55xovsthHtgewQBUWIRQke5jbqeykzT+bkiKjWT+9YW/uDZilUn6fulqQoZegnalLGNr07XoqC6aUjDRkchO8TBNmHdPnGBwCXhAZp1jjq2+cPQHxF/yQ4vRfEVhecjCo/YVVWcS440WSeChjJk/a8wCqrV6ps8WXMkwFpV2BCtNZTjgGp4j5ymd3j4CIe3CKxtiMTFfAMjgiwXLrlcXZEKdRupIYJfAbdi9iokKwz+LkcuujkvYmfSoug2EKzQIxVIJujnh2nysgk3c+WcmIIPTJM6wJUHBhyZdlqhSUT4I+crMFwNPs1z9RMVBJxZu1Th8wx2M4xqTwXBR8pQRzft1QeCgJdSMpaYg/8mr/tAAQ6JNu/JQIo6sV5y50IWCtEE78iEmf4OwY5IoL29InwuO0FzXKiTo3efIFMBS6YpH77X6V4pdGuuNSNHbIwQ+IzgqdvmHabQDHD/c0/jefeiunol1nixoJWkoZoIzUiU8ss8GCYzRi7NBdQh4/9H6PXFK9IAZGrF+K4oX63/BQuKl9JsKGoxN1u/DI="
