language: node_js
node_js:
  - node
warnings_are_errors: false
before_script:
  - npm install firebase-tools -g
install:
  - npm install
script:
  - CI=false npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: GYOCs7kouCIMGXangF4VVlNy50YFImDCjdOy5CJ1tyuIFlzY0fq09B8pFcKs6zA7EgGkSCVSCPosp0ICCO3B04vwlmfC2E7EpjefHAJN1fiAF11Sb8fcC9JA4dA8IT5jW44keEQK8kAOx1xmHzsYYqV5y4Pe+6qjgiORspgst0wBAv/JND4h5lcxdlxZXTYBNATvjy2g3LZGUTIuxN0JxD72um78yTQ10orPQdf4qsidRmwJbztQu2aLwbw3g++SYH9mlSsCUF85/rxlSSL7Cx7luXoiMI8kgZ7ZldAY54Ss4QShQH3k+O3JUzNgfR0yaJ37qcdjkvTJz3vqUO6WO0o5IGSzFbjKb7YrYvWPtEz/dyuHn14H7r8Z+u1iEaYyG2+0Ev4O+w5ZuW1LIHCYM+aYXh5QSY4hO9mqZRucvnrRbK/d8VoRiQN3vYzCVUGqyGhdSkCoqBmGWlCeIQFCzpr7/f4UCMLd2eY/pY8lr3V1fqB3zx5KuTh6FyD/vUTfa2VMQSAq1O/NgTdYj2BCsFMZGlWC95YtVTEfncsje7Z/jhkuaw/2hoOWWIdI4FF5lCd6b9Ctl4J1xYhDBb5VACaGe9J58LXWdpEKBCqCBOMdqcHFabmyxMhDNAGPTqQJvtz3lLe4huatKFICKjUowTflmGIYsJr29Y96YmSf46M=
  project: "poker-analytics-3ba9f"