language: node_js
node_js:
  - node
warnings_are_errors: false
before_script:
  - npm install firebase-tools -g
install:
  - npm install
script:
  - CI=false npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: kLgnu3rl4s8CPaSlABLi4xpuCzMXfWdcfrQEEGLlgdVklmK+lKxxYwJxe7BNGEhNq777TdZmxgFa6b3N7Ll7oGUXqLAnHKZrtc56xQOpk+WbIzhovFJI5REM2VimaieL5Z0PD+mhuO/v7rvDVe9kS8WS1aWzSfnRmdut5jmwcrz+BrJ0JrqHij2S5BKYiuzKc9PzZtVnqCz8rUyJjziOtthaGqTunSO2y0TZAVKYq4LemdIsURiSol2Sf8g+oZ0rUvTiUtt2MRcIEKAWHtP09vtGHjNtWGsHIgS+j5eKO+V/cagMHbvCz33G4KEa/09YirLQd3DpUhk3wewBuWrVMqDK+swYUI/EIcvyyrvPEphp5C7/JDUGwPh/NzCcBaDV4GXVT6uUf78Y02ThCxWybzdhElN9S0AvPuFVK94sxHKVeY/jtXs9F87mDVyOzq93MFaC93guS1InCBR599t37j8WH7bSNWMK7CCwY6hqPOBrvH32Ffot1Q6+Xyuof4D1n2s7KonVxyve403nsOd9QlEwV1pL2o/88N1uOyORb+TneZ7TVfn7DXmPpTvxxGbs+XRZfGS3erEyaYQGWum5kyKoeTkn/Fsqhn/VddAQiTxeJwA1pzhQw4lqWykXiRPQ1tPpLTA5fdzzvhPU/yLNN+6pUNqdNqPafZv+NH3/cjM=
