language: node_js
node_js:
  - node
warnings_are_errors: false
before_script:
  - npm install firebase-tools -g
install:
  - npm install
script:
  - CI=false npm run build
  - firebase deploy --only hosting --token ${TOKEN}
