language: node_js
node_js:
  - node
warnings_are_errors: false
before_script:
  - npm install firebase-tools -g
install:
  - npm install
env:
  global:
    - REACT_APP_API_KEY=$API_KEY
    - REACT_APP_AUTH_DOMAIN=$AUTH_DOMAIN
    - REACT_APP_DATABASE_URL=$DATABASE_URL
    - REACT_APP_PROJECT_ID=$PROJECT_ID
    - REACT_APP_STORAGE_BUCKET=$STORAGE_BUCKET
    - REACT_APP_MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID
    - REACT_APP_APP_ID=$APP_ID
    - REACT_APP_MEASUREMENT_ID=$MEASUREMENT_ID
script:
  - CI=false npm run build
  - firebase deploy --only hosting --token $TOKEN
