language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - CI=false npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "cs5AcA2G4rATa1mzEAhs4ORKLms1Zs8MaVp5kodwamNU72Pr+j0rCwsOE3Mg/SeSxAsslYjIPkF3wBRjQtgX+widh0U63YkFDyEjK2DrwSOKh+qI05jO+1sla2o2ZTBTj1AmaOp1/vZ8dh2OBufrT7tPHYZDFJ0Bs/t8lhKgktvc1F8k6lAbu6Dm9gGh1JyA5GcAnjXnG/3PEzGd5ZYtNW+2LtWTt3OgE6P7JpxfCXeVQSe9qf11822vJR24tAFERoiNhdwMubnhX4z4vkApdJSIdmG8nL06rEY/tJmkUMIQibF32LV/erGWXb/PFJoA8Bh7ljPL7LsMWCqdgA5CZpaO5tOeMQ2tF3uT5J/NIVqaFP/zSAbQOdmiRxjhbxRzK5rXz+580T+BpS1HkDqlfU/P21Cv9pkt1oGnuTjPcvhcUicYJWszPqPfyScb4JuuHfthsZ7Fmxp/W926wYZf+g5jGHtHDeufBzDQj06OkPqlRY1hnweVryBhRpOpqNOYv5/UBB//9etubFzR7wKUbGwvixAqR/RMNsVLyrjcTDt1NSszJhnOad6aTQUkBKbmOPNng06VxTHwM8VYGKtC0TEhvC+YYVJk0toj/ul78r5ZB+6ibnAAlVz6yKvENYm8pXVjTpwJGfROoNMarFgwVhVPskGjpHD88MZ0V844IcA="
